Revert "Register"
PurePassersBy/ShacoBomber pull request #6
Opened 2022-07-09 03:32 UTC by zixun-taiben

Reverts PurePassersBy/ShacoBomber#4

2022-07-10 04:21 UTC, zixun-taiben commented on bomber/server/networkutils.h
> +}
It better to encapsulate some useful function in a utils file.

2022-07-10 04:22 UTC, zixun-taiben commented on bomber/server/mysqlutils.cpp
> +}
See also here.

2022-07-10 04:43 UTC, GanbatteKnight commented on bomber/server/networkutils.h
> +}
I can't agree more.  It looks much formal  since you use template

2022-07-11 01:16 UTC, GanbatteKnight commented on bomber/server/mysqlutils.cpp
> +}
> Since hundreds of lines of codes have been committed, I am afraid that there exists some errors or bad designs which would accumulate to result in a disaster later if without different views in the process.
> 
> Could u plz review the commits and give some comments and suggestions? thx! @GanbatteKnight

The code are all doing good except for the interface "mysqlutils". The table and mysql statement used in register and login part are relatively fixed, which means we can disassemble "mysqlutils" further into four part: add、delete、edit and  search so that there is no code like
 ```
 string getPasswdStmt = "SELECT password FROM t_user_info WHERE mobile=? LIMIT 1;";
string passwdOut = stmt_query_opors(m_mysql, getPasswdStmt, usernameIn);
```
It's important to guarantees the reusability of database utils in a high abstract level and reduce the combination of the code coupling.  That's the reason why mysql statement is not supposed to be in the 'server.cpp'.
By the way, you really did a greate and heavy work so far. Your work is an encouragement to the whole Shaco Tech.

2022-07-11 01:26 UTC, GanbatteKnight requested changes
The code are all doing good except for the interface "mysqlutils". The table and mysql statement used in register and login part are relatively fixed, which means we can disassemble "mysqlutils" further into four part: add、delete、edit and  search so that there is no code like
 ```
 string getPasswdStmt = "SELECT password FROM t_user_info WHERE mobile=? LIMIT 1;";
string passwdOut = stmt_query_opors(m_mysql, getPasswdStmt, usernameIn);
```
It's important to guarantees the reusability of database utils in a high abstract level and reduce the combination of the code coupling.  That's the reason why mysql statement is not supposed to be in the 'server.cpp'.
By the way, you really did a greate and heavy work so far. Your work is an encouragement to the whole Shaco Tech.@zixun-taiben

2022-07-11 08:20 UTC, GanbatteKnight commented
> Oops! Did you mean using something like `string queryPasswdByUsername(string username)` ?
> 
> I think you are right. The string 'SELECT ...' should not exist in `server.cpp` I will refactor it later this day. Thx for the instructive suggestions~

We are on the same page now. Server part should put more emphasis on working logic instead of how to write mysql statement. It might be more decoupling if you can provide some abstract  mysql interface to server part, which allows developers to use just combinations of mysqlutils function and execute sql query flexibly too. 
You're welcome :)

2022-07-16 15:18 UTC, GanbatteKnight commented
> Basic functions of register and login have been done! 🥇 Some enhancements such as promt to user, exception handling are expected to do later.
> 
> Anyway, the whole process of register and login is fullfilled. @GanbatteKnight Plz test the process and review the code. thx!

Thanks for your hardworkings! I just got home and will be right back to my position admiring your masterpiece tomorrow.  Lockstep server hopefully will be done in two days. I can't wait to see ShacoBomber overall running.

2022-07-17 02:10 UTC, GanbatteKnight approved these changes
I think the code clean and clear. And I learn a lot from the server part in your work. But I have a question: why the function name in 'utils.cpp' written in underscore case instead of Camel case?

2022-07-17 02:12 UTC, merged